/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as CreateRouteImport } from './routes/create'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiAwakenRouteImport } from './routes/api/awaken'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as PersonaIdRouteImport } from './routes/persona.$id'
import { Route as ApiTurnCredentialsRouteImport } from './routes/api/turn/credentials'
import { Route as ApiVoiceCloneRouteImport } from './routes/api/voice/clone'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice/tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwakenRoute = ApiAwakenRouteImport.update({
  id: '/api/awaken',
  path: '/api/awaken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIdRoute = PersonaIdRouteImport.update({
  id: '/persona/$id',
  path: '/persona/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnCredentialsRoute = ApiTurnCredentialsRouteImport.update({
  id: '/api/turn/credentials',
  path: '/api/turn/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceCloneRoute = ApiVoiceCloneRouteImport.update({
  id: '/api/voice/clone',
  path: '/api/voice/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice/tts',
  path: '/api/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/create': typeof CreateRoute
  '/places': typeof PlacesRoute
  '/world': typeof WorldRoute
  '/api/awaken': typeof ApiAwakenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/status': typeof ApiStatusRoute
  '/persona/$id': typeof PersonaIdRoute
  '/api/turn/credentials': typeof ApiTurnCredentialsRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/create': typeof CreateRoute
  '/places': typeof PlacesRoute
  '/world': typeof WorldRoute
  '/api/awaken': typeof ApiAwakenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/status': typeof ApiStatusRoute
  '/persona/$id': typeof PersonaIdRoute
  '/api/turn/credentials': typeof ApiTurnCredentialsRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/create': typeof CreateRoute
  '/places': typeof PlacesRoute
  '/world': typeof WorldRoute
  '/api/awaken': typeof ApiAwakenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/status': typeof ApiStatusRoute
  '/persona/$id': typeof PersonaIdRoute
  '/api/turn/credentials': typeof ApiTurnCredentialsRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circle'
    | '/create'
    | '/places'
    | '/world'
    | '/api/awaken'
    | '/api/chat'
    | '/api/status'
    | '/persona/$id'
    | '/api/turn/credentials'
    | '/api/voice/clone'
    | '/api/voice/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circle'
    | '/create'
    | '/places'
    | '/world'
    | '/api/awaken'
    | '/api/chat'
    | '/api/status'
    | '/persona/$id'
    | '/api/turn/credentials'
    | '/api/voice/clone'
    | '/api/voice/tts'
  id:
    | '__root__'
    | '/'
    | '/circle'
    | '/create'
    | '/places'
    | '/world'
    | '/api/awaken'
    | '/api/chat'
    | '/api/status'
    | '/persona/$id'
    | '/api/turn/credentials'
    | '/api/voice/clone'
    | '/api/voice/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircleRoute: typeof CircleRoute
  CreateRoute: typeof CreateRoute
  PlacesRoute: typeof PlacesRoute
  WorldRoute: typeof WorldRoute
  ApiAwakenRoute: typeof ApiAwakenRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiStatusRoute: typeof ApiStatusRoute
  PersonaIdRoute: typeof PersonaIdRoute
  ApiTurnCredentialsRoute: typeof ApiTurnCredentialsRoute
  ApiVoiceCloneRoute: typeof ApiVoiceCloneRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awaken': {
      id: '/api/awaken'
      path: '/api/awaken'
      fullPath: '/api/awaken'
      preLoaderRoute: typeof ApiAwakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$id': {
      id: '/persona/$id'
      path: '/persona/$id'
      fullPath: '/persona/$id'
      preLoaderRoute: typeof PersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turn/credentials': {
      id: '/api/turn/credentials'
      path: '/api/turn/credentials'
      fullPath: '/api/turn/credentials'
      preLoaderRoute: typeof ApiTurnCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/clone': {
      id: '/api/voice/clone'
      path: '/api/voice/clone'
      fullPath: '/api/voice/clone'
      preLoaderRoute: typeof ApiVoiceCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/tts': {
      id: '/api/voice/tts'
      path: '/api/voice/tts'
      fullPath: '/api/voice/tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircleRoute: CircleRoute,
  CreateRoute: CreateRoute,
  PlacesRoute: PlacesRoute,
  WorldRoute: WorldRoute,
  ApiAwakenRoute: ApiAwakenRoute,
  ApiChatRoute: ApiChatRoute,
  ApiStatusRoute: ApiStatusRoute,
  PersonaIdRoute: PersonaIdRoute,
  ApiTurnCredentialsRoute: ApiTurnCredentialsRoute,
  ApiVoiceCloneRoute: ApiVoiceCloneRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
